### ISSUE TITLE
Tolls - multiple units per path problem

### ISSUE THREAD

**Issue by mbradds** [mbradds/pipeline-profiles#112]
Brianne,
I'm not sure what to do when the toll unit "changes" halfway through one of the paths. The chart can only have one y-axis unit, and smoothing out the units between different currencies would be difficult. There are three instances where this happens (listed below). Can you take a look at these and see if something can be done? If the units cant be "standardized" then we'll need to come up with an approach to display these corner cases accurately on the dashboard.

1)
Pipeline: Cochin
Path: International Boundary near Alameda, Saskatchewan-Facilities in Fort Saskatchewan, Alberta
Units: Changes from **$ per cubic metre** to **USD$ per cubic metre** at **Effective Start 2016-07-01**

2)
Pipeline: Genesis
Path: All paths
Units: Changes from **cubic metre** to **$ per barrel** at **Effective Start 2009-03-01**

3)
Pipeline: EnbridgeLocal
Path: Edmonton Terminal, Alberta-International Boundary near Gretna, Manitoba and Edmonton Terminal, Alberta-Hardisty Terminal, Alberta
Units: Changes from **DOLLARS PER CUBIC METRE** to **CAD DOLLARS PER CUBIC METRE** at **Effective Start 2015-04-01**

**Comment by briannne** [comment]
1. **Cochin:** The company switched reporting from Canadian dollars to US dollars. I don't think this one can be standardized, unless we want to do a conversion. But that can get messy with the conversion rates. It looks like, based on the [current pipeline profile](https://www.cer-rec.gc.ca/en/data-analysis/facilities-we-regulate/pipeline-profiles/oil-and-liquids/pipeline-profiles-kinder-morgan-cochin.html), that we just set each currency as it's own data series. Can/should we continue with that? I'll try to think of something better. In the meantime, I changed $ per cubic metre to **CAD$ per cubic metre**. Hopefully that makes it more clear that there are two currencies being reported.

2. **Genesis:** Fixed. All units should now be in **$ per barrel**.

3. **EnbridgeLocal:** Fixed. All units should now be in **CAD DOLLARS PER CUBIC METRE**.

**Comment by mbradds** [comment]
Cochin fixed with 95eaea2
