### ISSUE TITLE
Tolls - NGTL

### ISSUE THREAD

**Issue by briannne** [mbradds/pipeline-profiles#116]
1. Rename buttons to the following:  

- Average Firm Transportation - Delivery (FT-D)
- Average Firm Transportation - Receipt (FT-R)

2. Convert both to $/GJ/day. Only need to display this unit on the axis. 

- for FT-D: [Toll]*12/365
- for FT-R: [Toll]*12/365/37.8

**Comment by mbradds** [comment]
Fixed with 0a36917
