### ISSUE TITLE
5-year average analysis for traffic data

### ISSUE THREAD

**Issue by MargaretSkwara1** [mbradds/pipeline-profiles#18]
Add additional wording for the throughput analysis text box. 
As of the most recent quarterly update, throughputs at the  Edmonton  key point have increased by 2% year over year, from an average of 1.08 Bcf/d in Q4 2019 to an average of 1.10 Bcf/d in Q4 2020 (most recent quarter of data). Example: **Throughputs in Q4 2020 were down/up X% compared to the five-year average.**

**Comment by mbradds** [comment]
Added second trend paragraph for gas. Lmk if wording is ok.
https://pipeline-profiles.herokuapp.com/dist/en/natural-gas/ngtl_en.html

**Comment by MargaretSkwara1** [comment]
Tiny edit. Change 'are' to 'were'. Throughputs in Q4 2020 **are** 9% above the five year average.
