### ISSUE TITLE
Trans Mountain - Order of Key Points Trends and Description

### ISSUE THREAD

**Issue by briannne** [mbradds/pipeline-profiles#42]
**Trans Mountain Profile**

The order of key point in the *Trends* and *Description* box are not in the same order after applying the key points button filter. Not a big deal, but could help with consistency.

![TransMountain_KeyPoints](https://user-images.githubusercontent.com/85134273/120661013-222b9080-c445-11eb-80e5-c1566f67e76b.jpg)

**Comment by mbradds** [comment]
Fixed with daec09a
